version: '3.8'

services:
  sleek-airflow:
    image: apache/airflow:latest 
    container_name: airflow-sleek 
    environment:
      - AIRFLOW_HOME=/opt/airflow
      - AIRFLOW__CORE__LOAD_EXAMPLES=False 
      - AIRFLOW__CORE__EXECUTOR=SequentialExecutor 
      - PYTHONUNBUFFERED=1
    volumes:
      - ./airflow/dags:/opt/airflow/dags 
      - ./airflow/source:/opt/airflow/source
      - ./airflow/staging:/opt/airflow/staging
      - ./airflow/tests:/opt/airflow/tests
      - ./airflow/logs:/opt/airflow/logs 
      - ./airflow/plugins:/opt/airflow/plugins 
    ports:
      - "8080:8080" 
    command: airflow standalone 
    restart: always 
